server:
  port: 8000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/user_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  profiles:
    active: dev
  config:
    import: vault://
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 30s
        acl-token: ${CONSUL_TOKEN}
        fail-fast: false
        prefer-ip-address: true
    vault:
      kv:
        enabled: true
        default-context: ${spring.application.name}
        backend: genesis
      authentication: token
      token: ${VAULT_TOKEN:hvs.oRQnuUvCLMPYf1UQw0cEW3Yb}
      scheme: ${VAULT_SCHEME:http}
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
    function:
      definition: handleDebitBalanceCommand
    stream:
      bindings:
        handleDebitBalanceCommand-in-0:
          destination: debit-balance-topic
        handleDebitBalanceCommand-out-0:
          destination: debit-balance-reply-topic

resilience4j:
  circuitbreaker:
    instances:
      order-service-client:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      order-service-client:
        timeout-duration: 3s
  retry:
    instances:
      order-service-client:
        # retry for a maximum of 3 attempts, each with a delay of 3s.
        max-attempts: 3
        wait-duration: 3s
  bulkhead:
    instances:
      order-service-client:
        # allow max 10 concurrent requests
        maxConcurrentCalls: 10
        # when we get any additional requests for service when the existing 10 threads are busy,
        # we wait for only 10 ms and fail the request immediately
        maxWaitDuration: 10m

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
