version: '3.8'

name: genesis-logging

services:
  genesis-logging-elasticsearch:
    container_name: genesis-logging-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    restart: unless-stopped
    environment:
      node.name: es-node
      cluster.name: docker-cluster
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      xpack.license.self_generated.type: basic
      xpack.security.enabled: true
      ELASTIC_PASSWORD: genesis
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      interval: 30s
      retries: 10
      test: [ "CMD-SHELL", "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null --user elastic:genesis http://localhost:9200" ]
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - genesis-network

  genesis-logging-kibana:
    container_name: genesis-logging-kibana
    image: docker.elastic.co/kibana/kibana:8.10.4
    restart: unless-stopped
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    command: >
      bash -c "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null --user elastic:genesis http://genesis-infra-elasticsearch:9200/_security/user/kibana_system/_password -H 'Content-Type: application/json' -d '{\"password\": \"genesis\"}' && /usr/local/bin/kibana-docker"
    depends_on:
      genesis-infra-elasticsearch:
        condition: service_healthy
    networks:
      - genesis-network

  genesis-logging-logstash:
    container_name: genesis-logging-logstash
    image: docker.elastic.co/logstash/logstash:8.10.4
    restart: unless-stopped
    volumes:
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./docker/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./docker/logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    depends_on:
      genesis-infra-elasticsearch:
        condition: service_healthy
    networks:
      - genesis-network

  genesis-logging-filebeat:
    container_name: genesis-logging-filebeat
    image: docker.elastic.co/beats/filebeat:8.10.4
    restart: unless-stopped
    command: filebeat -e -strict.perms=false
    volumes:
      - ./docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - E:\logs:/logs
    depends_on:
      genesis-infra-logstash:
        condition: service_started
    networks:
      - genesis-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  genesis-network:
    external: true