version: '3.8'

name: genesis-ci

services:
  genesis-ci-docker:
    container_name: genesis-ci-docker
    image: docker:dind
    privileged: true
    restart: always
    command: --storage-driver overlay2
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - docker-data:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - "2376:2376"
    networks:
      ci:
        aliases:
          - docker

  genesis-ci-jenkins-server:
    container_name: genesis-ci-jenkins-server
    restart: always
    depends_on:
      genesis-ci-docker:
        condition: service_started
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - ci

  genesis-ci-sonarqube-server:
    container_name: genesis-ci-sonarqube-server
    image: sonarqube:alpine
    restart: always
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - ci

volumes:
  jenkins-docker-certs:
    driver: local
  jenkins-data:
    driver: local
  docker-data:
    driver: local
  sonarqube-data:
    driver: local
  sonarqube-logs:
    driver: local
  sonarqube-extensions:
    driver: local

networks:
  ci:
    driver: bridge
