version: '3.8'

name: genesis-monitor

services:
  genesis-monitor-prometheus:
    container_name: genesis-monitor-prometheus
    image: prom/prometheus:v2.48.1
    restart: always
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - genesis-network

  genesis-monitor-grafana:
    container_name: genesis-monitor-grafana
    image: grafana/grafana:10.2.2
    restart: always
    ports:
      - "3000:3000"
    networks:
      - genesis-network

volumes:
  prometheus:
    driver: local

networks:
  genesis-network:
    external: true
