server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import: vault://
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 30s
        acl-token: ${CONSUL_TOKEN}
        fail-fast: false
        prefer-ip-address: true
    vault:
      kv:
        enabled: true
        default-context: ${spring.application.name}
        backend: genesis
      authentication: token
      token: hvs.SxOv3K9RpSR0Xja8fr10FCUa
      scheme: http
      host: localhost
      port: 8200
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/oauth2/**, /api/auth/signup
          filters:
            - RewritePath=/api/oauth2/(?<segment>.*), /oauth2/$\{segment}
            - RewritePath=/api/auth/signup, /signup

management:
  endpoints:
    web:
      exposure:
        include: "*"
