server:
  port: 8010
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/product_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  profiles:
    active: dev
  config:
    import: vault://
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: ${server.servlet.context-path}/actuator/health
        health-check-interval: 30s
        acl-token: ${CONSUL_TOKEN}
        fail-fast: false
        prefer-ip-address: true
        query-passing: true
    vault:
      kv:
        enabled: true
        default-context: ${spring.application.name}
        backend: genesis
      authentication: token
      token: ${VAULT_TOKEN:hvs.oRQnuUvCLMPYf1UQw0cEW3Yb}
      scheme: ${VAULT_SCHEME:http}
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
    function:
      definition: handleReduceQuantityCommand;handleCompensateQuantityCommand
    stream:
      bindings:
        handleReduceQuantityCommand-in-0:
          destination: reduce-quantity-topic
        handleReduceQuantityCommand-out-0:
          destination: reduce-quantity-reply-topic
        handleCompensateQuantityCommand-in-0:
          destination: compensate-quantity-topic
        handleCompensateQuantityCommand-out-0:
          destination: compensate-quantity-reply-topic

logging:
  level:
    web: trace
    org.hibernate.orm.jdbc.bind: trace
    net.ttddyy.dsproxy.listener: debug

decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      multiline: true
      format-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
