server:
  port: 8030
  servlet:
    context-path: /query

spring:
  application:
    name: query-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/querying_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  profiles:
    active: dev
  config:
    import: vault://
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: ${server.servlet.context-path}/actuator/health
        health-check-interval: 30s
        acl-token: ${CONSUL_TOKEN}
        fail-fast: false
        prefer-ip-address: true
    vault:
      kv:
        enabled: true
        default-context: ${spring.application.name}
        backend: genesis
      authentication: token
      token: ${VAULT_TOKEN:hvs.oRQnuUvCLMPYf1UQw0cEW3Yb}
      scheme: ${VAULT_SCHEME:http}
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
    function:
      definition: handleCreateCategoryCommand;handleUpdateCategoryCommand;handleCreateOrderCommand;handleUpdateOrderCommand;handleCreateUserCommand;handleUpdateUserCommand;handleCreateProductCommand;handleUpdateProductCommand
    stream:
      bindings:
        handleCreateCategoryCommand-in-0:
          destination: create-category-topic
        handleUpdateCategoryCommand-in-0:
          destination: update-category-topic
        handleCreateOrderCommand-in-0:
          destination: create-order-topic
        handleUpdateOrderCommand-in-0:
          destination: update-order-topic
        handleCreateUserCommand-in-0:
          destination: create-user-topic
        handleUpdateUserCommand-in-0:
          destination: update-user-topic
        handleCreateProductCommand-in-0:
          destination: create-product-topic
        handleUpdateProductCommand-in-0:
          destination: update-product-topic

logging:
  level:
    web: trace
    org.hibernate.orm.jdbc.bind: trace
    net.ttddyy.dsproxy.listener: debug

decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      multiline: true
      format-sql: true

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
